# General build informations
language: node_js
sudo: required
dist: xenial
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '11'
  - '8'
  - '6'
script:
  - npm run test:prod && npm run build
